config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'} do
  	resources :orders
  	end
  	
  get 'cart/index'

  resources :tutors

  resources :lessons

  resources :orders do
  	resources:orderlessons
  end

  resources :categories

root 'static_pages#home'

get '/about' => 'static_pages#about'

get '/lessons' => 'static_pages#lessons'

get '/tutors' => 'static_pages#tutors'

#get '/login' => 'user#login'

#get '/logout' => 'user#logout'

get '/cart', to: 'cart#index'
  
get '/cart/:id', to: 'cart#add'
  
get '/clearcart', to: 'cart#clearCart'
  
get '/cart/remove/:id' => 'cart#remove'
  
get '/cart/decrease/:id' => 'cart#decrease'
  
get '/cart/increase/:id' => 'cart#increase'
  
get '/checkout' => 'cart#createOrder'
  
get '/paid/:id' => 'static_pages#paid'
  
get '/users' => 'static_pages#users'
  
get '/upgrade/:id' => 'static_pages#upgrade'
  
get '/upgrade/:id' => 'static_pages#downgrade'
  
post '/search' => 'lessons#search'
  
get '/search' => 'static_pages#searchproducts'
  
get 'category/:title', to: 'static_pages#categories'
  
get '/bag/:id', to: 'cart#bag'
 # get 'static_pages/home'
 # get 'static_pages/tutors'
 # get 'static_pages/lessons'
 # get 'static_pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def tutors
  end

  def lessons
  end

  def about
  end

  def choosecategory
    @orders = Order.all
    @orderlessons = Orderlesson.all
    @lessons = Lesson.all
    
    @categories = Category.all
    @page_title = "Choose a Category"
  end

  def categories
    catName = params[:title]
    @lessons = Lesson.where("category like ?", catName) #might need to be changed to ("categories like ?, catName")
    @page_title = "Book a Course"
  end


  def paid
    # redirect_to "/cart/clear"
    flash[:notice] = 'Transaction Complete'
    @order = Order.last
    @order.update_attribute(:status , "Paid by User: #{current_user.email}")
    #"Paid by User:#{current_user.id} #{current_user.name} #{current_user.surname}")
    session[:cart] = nil
    
    @orders = Order.all
    @orderlessons = Orderlesson.all
    @lessons = Lesson.all
    
  end

  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title, "About Vivace") %>

<h2>About Vivace</h2>

<p>Vivace allows you to easily find a music instrument course, find out some information about it and the tutor delivering the course.  If you are interesting in attending one of our courses you can book and pay online. Then simply turn up on the evening of your course start date and enjoy learning your instrument in a friendly and welcoming environment.-</p>

<p>All of our tutors have spent years playing in bands, orchestras, ensembles covering a myriad of genres.  You can find our more about our tutors on this site on <%= link_to "this page", tutors_path %></p>

<!--<p>We are based in the centre of Dublin with plentiful public transport options. There is also a private parking garage nearby</p>-->
<hr>
<div class="row">
  <div class="col-md-6">
    <h5>Our address</h5>

    <p>3A Mayor Street Upper, Spencer Dock, Dublin 1</p>

    <h5>Phone</h5>

    <p><%= number_to_phone "0868886632" %></p>

    <h5>Email</h5>

    <p><a href="mailto:jcbrennan@gmail.com?subject=VivaceContact" "email me">Email me</a> </p>
  </div>

  <div class="col-md-6">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2381.67556726897!2d-6.240511248904055!3d53.349063582111015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48670ef2e498f9e1%3A0x88cbefc85d201cf2!2s3A%20Mayor%20Street%20Upper%2C%20North%20Wall%2C%20Dublin%201%2C%20D01%20PF72!5e0!3m2!1sen!2sie!4v1587249649322!5m2!1sen!2sie" width="300" height="250" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  </div>
</div>

app/views/static_pages/categories.html.erb
<p id="notice"><%= notice %></p>
<div id="lessonsContainer">
<title>Lessons</title>
<% if @lessons.length == 0  %>
<br />
<h2>There are currently no courses available in this category</h2>
<% end %>

    <% @lessons.each do |Lessons| %>
      <div class="lessonhols">
        <h1><%= lesson.title %></h1>
        <%= link_to (image_tag lesson.image_url, :class=>"lessonholsIm"), lesson %>
       <p><%= lesson.description %>
       </p>
       <p><%= lesson.price %>
        <br>
        <%= lesson.category %>
        </p>
        <p>        
         
          <a href="/cart/<%= lesson.id %>" class="button">Add to Cart</a>  
          <%= link_to 'Show', lesson, :class =>"button", :role=>"button" %>
        

        <% if session[:login] == 1 %> 
        <%= link_to 'Edit', edit_lesson_path(item), :class =>"button", :role=>"button" %>
        <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button",           :role=>"button" %>
        
        <% end %>
        </p>
     </div>
    <% end %>
  <br>

app/views/static_pages/choosecategory.hrml.erb
<h1> Choose which instrument you wish to learn</h1>

<%=render 'layouts/categories' %>

app/views/static_pages/home.html.erb
<main role="main" class="inner cover">
  <h1 class="cover-heading">Welcome</h1>
  <p class="lead">Vivace music school provides courses and lessons covering all musical abilities and many musical instruments</p>
  <p class="lead">
    <%= link_to "View Courses", categories_path, class: "btn btn-lg btn-secondary" %>
  </p>
</main>

app/views/static_pages/lessons.html.erb
<h1>Courses</h1>

<p> Welcome <%=current_user.first_name %></p>

app/views/static_pages/paid.html.erb
<h1 align="center">Thank you</h1>
<h2 align="center">Your order has been placed</h2>
<h3 align="center">Similar items recently bought</h3>
<div id="lessonsContainer">
  
  
     
      <% @orderlessons.order(id: :desc).limit(4).each  do |orderlesson| %>
      <div class="lessonhols">
       <h1><%= orderlesson.title %></h1> 
       <%= link_to (image_tag orderlesson.image_url, :class => "lessonholsIm"), @lesson %>
       
       <p><%= orderlesson.description %></p>
       <a href="/items/<%= orderlesson.lesson_id %>" class="button">View Lesson</a>
      
        
      </div>
    <% end %>
      


<br>

app/views/static_pages/searchproducts.html.erb
<div class = "searchBar"><%=render 'layouts/search'%></div>

app/views/static_pages/tutors.html.erb
<h1>StaticPages#tutors</h1>
<p>Find me in app/views/static_pages/tutors.html.erb</p>