config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'} do
  	resources :orders
  	end
  	
  get 'cart/index'

  resources :tutors

  resources :lessons

  resources :orders do
  	resources:orderlessons
  end

  resources :categories

root 'static_pages#home'

get '/about' => 'static_pages#about'

get '/lessons' => 'static_pages#lessons'

get '/tutors' => 'static_pages#tutors'

#get '/login' => 'user#login'

#get '/logout' => 'user#logout'

get '/cart', to: 'cart#index'
  
get '/cart/:id', to: 'cart#add'
  
get '/clearcart', to: 'cart#clearCart'
  
get '/cart/remove/:id' => 'cart#remove'
  
get '/cart/decrease/:id' => 'cart#decrease'
  
get '/cart/increase/:id' => 'cart#increase'
  
get '/checkout' => 'cart#createOrder'
  
get '/paid/:id' => 'static_pages#paid'
  
get '/users' => 'static_pages#users'
  
get '/upgrade/:id' => 'static_pages#upgrade'
  
get '/upgrade/:id' => 'static_pages#downgrade'
  
post '/search' => 'lessons#search'
  
get '/search' => 'static_pages#searchproducts'
  
get 'category/:title', to: 'static_pages#categories'
  
get '/bag/:id', to: 'cart#bag'
 # get 'static_pages/home'
 # get 'static_pages/tutors'
 # get 'static_pages/lessons'
 # get 'static_pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
 <div class="inner">
   <p class="app-footer"> <%= @copyright %> </p>
 </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand"><b>Vivace</b></h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
      
    </nav>
  </div>
</header>

app/views/shared/_lesson_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_lesson_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Our Services</h1>
      <p class="lead text-muted">Music learning courses for every level and (almost) every instrument facilitated by experienced tutors in a relaxed but professional setting. Just click on a button below</p>
      <p>
        <%=link_to 'Course Types', categories_path, class: 'btn btn-secondary' %>
        <%=link_to 'All Courses', lessons_path, class: 'btn btn-secondary' %>
        <%=link_to 'Our Tutors', tutors_path, class: 'btn btn-secondary' %>
      </p>
    </div>
</section>

app/views/shared/_lesson_nav.html.erb
<header>
	  <div class="collapse bg-dark" id="navbarHeader">
	    <div class="container">
	      <div class="row">
	        <div class="col-sm-8 col-md-7 py-4">
	          <h4 class="text-white">About these pages</h4>
	          <p class="text-muted">By using the buttons below, you can navigate to an overview of all the course types we provide as well as a detailed list of all courses as well as some information about our tutors. If you wish to book a course with us, just click on its photo to be taken to the detailed view where you can book from.</p>
	        </div>
	        <div class="col-sm-4 offset-md-1 py-4">
	          <h4 class="text-white">Explore</h4>
	          <ul class="list-unstyled">
	            <%= nav_helper 'text-white', 'li' %>
				<li><%= login_helper 'text-white' %></li>
	          </ul>
	        </div>
	      </div>
	    </div>
	  </div>
	  <div class="navbar navbar-dark bg-dark shadow-sm">
    	<div class="container d-flex justify-content-between">
      		<a href="#" class="navbar-brand d-flex align-items-center">
        	<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        	<strong>Vivace</strong>
      		</a>
      		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        	<span class="navbar-toggler-icon"></span>
      		</button>
    	</div>
  	</div>
</header>

app/views/shared/_nav.html.erb
 <!--<div class = "<%=location %>">
    <div><%#= link_to "Home", "/" %></div>
    <div><%#= link_to "About", about_path %></div>
    <div><%#= link_to "Lessons", lessons_path %></div>
    <div><%#= link_to "Tutors", tutors_path %></div>
 </div>-->