config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'} do
  	resources :orders
  	end
  	
  get 'cart/index'

  resources :tutors

  resources :lessons

  resources :orders do
  	resources:orderlessons
  end

  resources :categories

root 'static_pages#home'

get '/about' => 'static_pages#about'

get '/lessons' => 'static_pages#lessons'

get '/tutors' => 'static_pages#tutors'

#get '/login' => 'user#login'

#get '/logout' => 'user#logout'

get '/cart', to: 'cart#index'
  
get '/cart/:id', to: 'cart#add'
  
get '/clearcart', to: 'cart#clearCart'
  
get '/cart/remove/:id' => 'cart#remove'
  
get '/cart/decrease/:id' => 'cart#decrease'
  
get '/cart/increase/:id' => 'cart#increase'
  
get '/checkout' => 'cart#createOrder'
  
get '/paid/:id' => 'static_pages#paid'
  
get '/users' => 'static_pages#users'
  
get '/upgrade/:id' => 'static_pages#upgrade'
  
get '/upgrade/:id' => 'static_pages#downgrade'
  
post '/search' => 'lessons#search'
  
get '/search' => 'static_pages#searchproducts'
  
get 'category/:title', to: 'static_pages#categories'
  
get '/bag/:id', to: 'cart#bag'
 # get 'static_pages/home'
 # get 'static_pages/tutors'
 # get 'static_pages/lessons'
 # get 'static_pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :title

	has_many :lessons

	mount_uploader :image_url, CourseUploader

	
	extend FriendlyId
	friendly_id :name, use: :slugged
	

	def self.by_position
		order("position ASC")
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout "lessons"

  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.by_position
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :description, :image_url)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="btn btn-primary">
      Upload an image file <%= form.file_field :image_url, style: 'display:none;' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save Category', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class = "container admin-form">

	<h1>Editing Category</h1>

	<%= render 'form', category: @category %>

	<%= link_to 'Show', @category %> |
	<%= link_to 'Back', categories_path %>

</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% @categories.each do |category| %>
         <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <%= link_to (image_tag category.image_url.url, width: '100%'), category %>
            <div class="card-body">
              <p class="card-text">
                <span><%link_to category.title, lessons_path(category)%></span><p><%= category.title %></p><p><%= category.description %></p> 
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <!--<div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted"></small>-->
              </div>
            </div>
          </div>
         </div>
        <% end %>
      </div>
    </div>
  </div>

<!--<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @categories.each do |category| %>
      <tr>
        <td><%#= image_tag category.image %></td>
        <td><%#= category.title %></td>
        <td><%#= category.description %></td>        
        <td><%#= link_to 'Show', category %></td>
        <td><%#= link_to 'Edit', edit_category_path(category) if logged_in?(:site_admin) %></td>
        <td><%#= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>-->

<%= link_to 'New Category', new_category_path if logged_in?(:site_admin)%>

app/views/categories/new.html.erb
<div class = "container admin-form">

	<h1>New Category</h1>

	<%= render 'form', category: @category %>

	<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class = "container">
  <div class = "row-show">
    <div class = "row">
    <div class = "col-md-7">
      <%= image_tag @category.image_url.url, width: '100%' %>
    </div>

    <div class = "col-md-5">
      <h1><%= @category.title %></h1>
      <hr>
      <em><%= @category.description %></em>
      <hr>
      <%=link_to "View all course types", categories_path %> 
      <%= link_to '| Edit', edit_category_path(@category) if logged_in?(:site_admin)%>      
    </div>
  </div>
  </div>
</div> 